### PR TITLE
Sam

### PR DESCRIPTION
**Pull request by samanyuneelson**

### CODE REVIEW

**Comment by athul** [comment]
@samanyuneelson could you resolve the conflicts? Just delete the part in the conflict manager

**Comment by samanyuneelson** [comment]
i did  change in the web editor but it keeps coming back again

**Comment by athul** [comment]
Which one is needed? The one on master or on Sam?

**Comment by samanyuneelson** [comment]
Let me look into it. The merge from akshay changed the less file.

**Comment by samanyuneelson** [comment]
Can i deploy my branch on travis to asses functionality. How would i do that, or is heroku better.

**Comment by athul** [comment]
Go with Heroku.... I'll configure travis by evening

**Pull request merged**
