### PR TITLE
Styles for the placement section

### PR DESCRIPTION
**Pull request by akzhy**

### CODE REVIEW

**Comment by samanyuneelson** [comment]
changes only on css?

**Comment by akzhy** [comment]
placement.php file has been uploaded, data is not added. Dummy contents are used

**Review by athul — APPROVED** [review]
LGTM

**Comment by athul** [comment]
We can revert this PR if any changes are neede

**Comment by athul** [comment]
We should add labels to the PR and Issue.... Easy to find what we're looking for without checking the whole PR

**Pull request merged**
